{
    "created": 1733508028.2599335,
    "duration": 0.23323869705200195,
    "exitcode": 1,
    "root": "C:\\Users\\RH\\Documents\\GitHub\\readnupdate-test",
    "environment": {},
    "summary": { "failed": 1, "total": 1, "collected": 1 },
    "collectors": [
        {
            "nodeid": "",
            "outcome": "passed",
            "result": [{ "nodeid": "src/python_testcases", "type": "Package" }]
        },
        {
            "nodeid": "src/python_testcases/test_sequential.py",
            "outcome": "passed",
            "result": [
                {
                    "nodeid": "src/python_testcases/test_sequential.py::test_search",
                    "type": "Function",
                    "lineno": 13
                }
            ]
        },
        {
            "nodeid": "src/python_testcases",
            "outcome": "passed",
            "result": [
                {
                    "nodeid": "src/python_testcases/test_sequential.py",
                    "type": "Module"
                }
            ]
        }
    ],
    "tests": [
        {
            "nodeid": "src/python_testcases/test_sequential.py::test_search",
            "lineno": 13,
            "outcome": "failed",
            "keywords": [
                "test_search",
                "test_sequential.py",
                "python_testcases",
                "src",
                "readnupdate-test",
                ""
            ],
            "setup": { "duration": 0.12002720002783462, "outcome": "passed" },
            "call": {
                "duration": 0.00039059994742274284,
                "outcome": "failed",
                "crash": {
                    "path": "C:\\Users\\RH\\Documents\\GitHub\\readnupdate-test\\src\\python_testcases\\test_sequential.py",
                    "lineno": 18,
                    "message": "assert 2 == 1\n +  where 2 = search(5, (1, 5, 10))"
                },
                "traceback": [
                    {
                        "path": "src\\python_testcases\\test_sequential.py",
                        "lineno": 18,
                        "message": "AssertionError"
                    }
                ],
                "longrepr": "def test_search():\n        # Test cases\n        assert search(42, (-5, 1, 3, 5, 7, 10)) == 6\n        assert search(42, [1, 5, 10]) == 3\n>       assert search(5, (1, 5, 10)) == 1\nE       assert 2 == 1\nE        +  where 2 = search(5, (1, 5, 10))\n\nsrc\\python_testcases\\test_sequential.py:18: AssertionError"
            },
            "teardown": {
                "duration": 0.000478199974168092,
                "outcome": "passed"
            }
        }
    ]
}
