{
    "created": 1741369312.2107985,
    "duration": 0.4286680221557617,
    "exitcode": 1,
    "root": "C:\\Users\\RH\\Documents\\GitHub\\readnupdate-test",
    "environment": {},
    "summary": { "failed": 2, "total": 2, "collected": 2 },
    "collectors": [
        {
            "nodeid": "",
            "outcome": "passed",
            "result": [{ "nodeid": "src/python_testcases", "type": "Package" }]
        },
        {
            "nodeid": "src/python_testcases/test_module.py",
            "outcome": "passed",
            "result": [
                {
                    "nodeid": "src/python_testcases/test_module.py::test_search",
                    "type": "Function",
                    "lineno": 4
                },
                {
                    "nodeid": "src/python_testcases/test_module.py::test_duplicate",
                    "type": "Function",
                    "lineno": 17
                }
            ]
        },
        {
            "nodeid": "src/python_testcases",
            "outcome": "passed",
            "result": [
                {
                    "nodeid": "src/python_testcases/test_module.py",
                    "type": "Module"
                }
            ]
        }
    ],
    "tests": [
        {
            "nodeid": "src/python_testcases/test_module.py::test_search",
            "lineno": 4,
            "outcome": "failed",
            "keywords": [
                "test_search",
                "test_module.py",
                "python_testcases",
                "src",
                "readnupdate-test",
                ""
            ],
            "setup": { "duration": 0.12112780002644286, "outcome": "passed" },
            "call": {
                "duration": 0.006595400016522035,
                "outcome": "failed",
                "crash": {
                    "path": "C:\\Users\\RH\\Documents\\GitHub\\readnupdate-test\\src\\python_programs\\sequential.py",
                    "lineno": 5,
                    "message": "UnboundLocalError: local variable 'i' referenced before assignment"
                },
                "traceback": [
                    {
                        "path": "src\\python_testcases\\test_module.py",
                        "lineno": 15,
                        "message": ""
                    },
                    {
                        "path": "src\\python_programs\\sequential.py",
                        "lineno": 5,
                        "message": "UnboundLocalError"
                    }
                ],
                "longrepr": "def test_search():\n        assert search(42, (-5, 1, 3, 5, 7, 10)) == 6\n        assert search(42, [1, 5, 10]) == 3\n        assert search(5, (1, 5, 10)) == 1\n        assert search(7, [1, 5, 10]) == 2\n        assert search(3, (1, 5, 10)) == 1\n        assert search(-5, (1, 5, 10)) == 0\n        assert search(10, (-5, -1, 3, 5, 7, 10)) == 5\n        assert search(-100, (-5, -1, 3, 5, 7, 10)) == 0\n        assert search(0, (-5, -1, 3, 5, 7, 10)) == 2\n>       assert search(100, []) == 0\n\nsrc\\python_testcases\\test_module.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nx = 100, seq = []\n\n    def search(x, seq):\n        for i in range(len(seq)):\n            if x <= seq[i]:\n                return i\n>       return i + 1\nE       UnboundLocalError: local variable 'i' referenced before assignment\n\nsrc\\python_programs\\sequential.py:5: UnboundLocalError"
            },
            "teardown": {
                "duration": 0.00041390000842511654,
                "outcome": "passed"
            }
        },
        {
            "nodeid": "src/python_testcases/test_module.py::test_duplicate",
            "lineno": 17,
            "outcome": "failed",
            "keywords": [
                "test_duplicate",
                "test_module.py",
                "python_testcases",
                "src",
                "readnupdate-test",
                ""
            ],
            "setup": {
                "duration": 0.00023939998936839402,
                "outcome": "passed"
            },
            "call": {
                "duration": 0.13532920001307502,
                "outcome": "failed",
                "crash": {
                    "path": "C:\\Users\\RH\\Documents\\GitHub\\readnupdate-test\\src\\python_testcases\\test_module.py",
                    "lineno": 19,
                    "message": "assert [] == [1, 2, 3]\n  \n  Right contains 3 more items, first extra item: \u001b[0m\u001b[94m1\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\n  Use -v to get more diff"
                },
                "traceback": [
                    {
                        "path": "src\\python_testcases\\test_module.py",
                        "lineno": 19,
                        "message": "AssertionError"
                    }
                ],
                "longrepr": "def test_duplicate():\n>       assert remove_extras([1, 1, 1, 2, 3]) == [1, 2, 3]\nE       assert [] == [1, 2, 3]\nE         \nE         Right contains 3 more items, first extra item: \u001b[0m\u001b[94m1\u001b[39;49;00m\u001b[90m\u001b[39;49;00m\nE         Use -v to get more diff\n\nsrc\\python_testcases\\test_module.py:19: AssertionError"
            },
            "teardown": {
                "duration": 0.0011962999997194856,
                "outcome": "passed"
            }
        }
    ]
}
